export const API_URL = {
  STUDENT_REGISTER: "/auth/register-student",
  TEACHER_REGISTER: "/auth/register-teacher",
  TEACHER_RESET_PASSWORD: "/auth/reset-teacher-password",
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  REFRESH_TOKEN: "/auth/refresh",

  DASHBOARD: "/admin/dashboard",
  TEACHER_DASHBOARD: "/teacher/dashboard",
  PROFILE: "/profile",
  OWN_PROFILE: "/auth/profile",

  STUDENT: "/students",
  TEACHER: "/teachers",
  BLOG: "/blogs",
  COURSES: "/courses",
  COURSE_CATEGORIES: "/courses/categories",
  ADMIN_BLOG: "/blogs/admin",
  ADMIN_BLOG_CATEGORY: "/blogs/admin/category",
  COUPON: "/coupons",
  SECTIONS: "/sections",
  EXERCISES: "/exercises",
  LESSONS: "/lessons",
  MOCK_TESTS: "/mock-tests",
  READING: "/reading",
  LISTENING: "/listening",
  QUESTION_GROUPS: "/question-groups",
  QUESTIONS: "/questions",
  ORDERS: "/orders",
  WRITING: "/writing",
  SPEAKING: "/speaking",
  CERTIFICATES: "/certificates",
  STUDY_SCHEDULE: "/study-schedule",
};
