
const courseCategory = [
    {
        id: 1,
        name: "IELTS",
        description: "Prepare for the IELTS exam with comprehensive resources and practice tests.",
    },
    {
        id: 2,
        name: "TOEFL",
        description: "Master the TOEFL exam with expert guidance and practice materials.",
    },
    {
        id: 3,
        name: "TOEIC",
        description: "Enhance your English skills for the TOEIC exam with targeted exercises and mock tests.",
    },
]

const course = [
    {
        id: 1,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 3.5 - 5.0+",
        difficulty_level: "3.5 - 5.0",
        price: 3400000,
        discountPrice: 3000000, 
    },
    {
        id: 2,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 3.5 - 5.0+",
        difficulty_level: "3.5 - 5.0",
        price: 5100000,
        discountPrice: 4000000, 
    },
    {
        id: 3,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 3.5 - 6.0+",
        difficulty_level: "3.5 - 6.0",
        price: 6000000,
        discountPrice: 5250000, 
    },
    {
        id: 4,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 3.5 - 6.0+",
        difficulty_level: "3.5 - 6.0",
        price: 8400000,
        discountPrice: 7250000, 
    },
    {
        id: 5,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 3.5 - 7.0+",
        difficulty_level: "3.5 - 7.0",
        price: 12000000,
        discountPrice: 10500000,
    },
    {
        id: 6,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 3.5 - 7.0+",
        difficulty_level: "3.5 - 7.0",
        price: 15000000,
        discountPrice: 13500000,
    },
    {
        id: 7,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 4.0, 4.5 - 5.0+",
        difficulty_level: "4.0 - 5.0",
        price: 3000000,
        discountPrice: 2850000,
    },
    {
        id: 8,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 4.0, 4.5 - 5.0+",
        difficulty_level: "4.0 - 5.0",
        price: 4000000,
        discountPrice: 3800000,
    },
    {
        id: 9,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 4.0, 4.5 - 6.0+",
        difficulty_level: "4.0 - 6.0",
        price: 5250000,
        discountPrice: 5000000,
    },
    {
        id: 10,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 4.0, 4.5 - 6.0+",
        difficulty_level: "4.0 - 6.0",
        price: 7250000,
        discountPrice: 6800000,
    },
    {
        id: 11,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 4.0, 4.5 - 7.0+",
        difficulty_level: "4.0 - 7.0",
        price: 10500000,
        discountPrice: 9750000,
    },
    {
        id: 12,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 4.0, 4.5 - 7.0+",
        difficulty_level: "4.0 - 7.0",
        price: 13500000,
        discountPrice: 12500000,
    },
    {
        id: 13,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 5.0, 5.5 - 6.0+",
        difficulty_level: "5.0 - 6.0",
        price: 3000000,
        discountPrice: 2850000,
    },
    {
        id: 14,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 5.0, 5.5 - 6.0+",
        difficulty_level: "5.0 - 6.0",
        price: 4000000,
        discountPrice: 3800000,
    },
    {
        id: 15,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 5.0, 5.5 - 7.0+",
        difficulty_level: "5.0 - 7.0",
        price: 6250000,
        discountPrice: 6000000,
    },
    {
        id: 16,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 5.0, 5.5 - 7.0+",
        difficulty_level: "5.0 - 7.0",
        price: 8250000,
        discountPrice: 7800000,
    },
    {
        id: 17,
        category_id: 1,
        title: "IELTS Self-Study Course",
        description: "IELTS 6.0, 6.5 - 7.0+",
        difficulty_level: "6.0 - 7.0",
        price: 4000000,
        discountPrice: 3800000,
    },
    {
        id: 18,
        category_id: 1,
        title: "IELTS Comprehensive Course",
        description: "IELTS 6.0, 6.5 - 7.0+",
        difficulty_level: "6.0 - 7.0",
        price: 6000000,
        discountPrice: 5700000,
    }
]

export const courseMockData = {
    courseCategory,
    course,
}